import { admitRuntimeAdminRequest } from "@/lib/admin-access-runtime";
import { adminFailure, adminSuccess } from "@/lib/admin-api";
import { AdminVariantConflictError, AdminVariantIdempotencyConflictError, AdminVariantNotFoundError, AdminVariantValidationError, deleteVariant, getVariant, updateVariant } from "@/lib/admin-variant-repository";

export const dynamic = "force-dynamic";
const MAX_BODY_BYTES = 64 * 1024;
type Context = { params: Promise<{ id: string }> };

export async function GET(request: Request, context: Context): Promise<Response> { const requestId=crypto.randomUUID(); const admission=await admitRuntimeAdminRequest(request); if(!admission.ok)return adminFailure(requestId,admission.status,admission.code,admission.message); const id=parseId((await context.params).id); if(id===null)return adminFailure(requestId,404,"NOT_FOUND","Không tìm thấy biến thể."); const result=await getVariant(id); return result?adminSuccess(requestId,result):adminFailure(requestId,404,"NOT_FOUND","Không tìm thấy biến thể."); }

export async function PATCH(request: Request, context: Context): Promise<Response> { const requestId=request.headers.get("x-request-id")?.trim()||crypto.randomUUID(); const admission=await admitRuntimeAdminRequest(request); if(!admission.ok)return adminFailure(requestId,admission.status,admission.code,admission.message); if(!isJson(request.headers.get("content-type")))return adminFailure(requestId,415,"UNSUPPORTED_MEDIA","Content-Type không được hỗ trợ."); const id=parseId((await context.params).id); if(id===null)return adminFailure(requestId,404,"NOT_FOUND","Không tìm thấy biến thể."); try{return adminSuccess(requestId,await updateVariant(id,await readJson(request),admission.actor.subject,requestId));}catch(error){return mapError(requestId,error);} }

export async function DELETE(request: Request, context: Context): Promise<Response> { const requestId=request.headers.get("x-request-id")?.trim()||crypto.randomUUID(); const admission=await admitRuntimeAdminRequest(request); if(!admission.ok)return adminFailure(requestId,admission.status,admission.code,admission.message); const id=parseId((await context.params).id); if(id===null)return adminFailure(requestId,404,"NOT_FOUND","Không tìm thấy biến thể."); const version=new URL(request.url).searchParams.get("version"); if(!version)return adminFailure(requestId,400,"INVALID_REQUEST","Thiếu version."); try{await deleteVariant(id,version,admission.actor.subject,requestId);return adminSuccess(requestId,{deleted:true});}catch(error){return mapError(requestId,error);} }

async function readJson(request:Request):Promise<unknown>{const length=Number(request.headers.get("content-length"));if(Number.isFinite(length)&&length>MAX_BODY_BYTES)throw new AdminVariantValidationError("Payload too large.");const bytes=await request.arrayBuffer();if(bytes.byteLength>MAX_BODY_BYTES)throw new AdminVariantValidationError("Payload too large.");try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw new AdminVariantValidationError("Malformed JSON request.");}}
function mapError(requestId:string,error:unknown):Response{if(error instanceof AdminVariantNotFoundError)return adminFailure(requestId,404,"NOT_FOUND","Không tìm thấy biến thể.");if(error instanceof AdminVariantConflictError)return adminFailure(requestId,409,"STALE_WRITE","Biến thể đã được thay đổi hoặc có xung đột.");if(error instanceof AdminVariantIdempotencyConflictError)return adminFailure(requestId,409,"IDEMPOTENCY_CONFLICT","Request ID đã được sử dụng cho payload khác.");if(error instanceof AdminVariantValidationError||error instanceof Error&&/invalid|required|integer|MOQ|tier|payload/i.test(error.message))return adminFailure(requestId,422,"VALIDATION_ERROR","Dữ liệu biến thể không hợp lệ.");return adminFailure(requestId,500,"INTERNAL_ERROR","Không thể hoàn tất thao tác quản trị.");}
function parseId(value:string){const id=Number(value);return Number.isSafeInteger(id)&&id>0?id:null;}
function isJson(value:string|null){return Boolean(value&&value.toLowerCase().split(";",1)[0].trim()==="application/json");}
