import "server-only";

import { getCloudflareContext } from "@opennextjs/cloudflare";
import { canonicalProductMutationPayload, decodeProductVersion, encodeProductVersion, normalizeProductInput } from "./admin-product.ts";

interface Statement { bind(...values: unknown[]): Statement; all<T = Record<string, unknown>>(): Promise<{ results: T[] }>; first<T = Record<string, unknown>>(): Promise<T | null>; run(): Promise<{ meta?: { changes?: number } }>; }
interface Database { prepare(sql: string): Statement; batch<T extends Statement>(statements: T[]): Promise<unknown>; }
interface Env { GIACONG_VN_CATALOG?: Database; }
export interface AdminProduct { id:number; name:string; slug:string; sku:string; shortDescription:string; description:string; imageUrl:string|null; categoryId:number|null; isActive:boolean; version:string; updatedAt:string; }
interface Row { id:number; name:string; slug:string; sku:string; short_description:string; description:string; image_url:string|null; category_id:number|null; is_active:number; revision:number; updated_at:string; }
export class AdminProductConflictError extends Error {}
export class AdminProductNotFoundError extends Error {}
export class AdminProductValidationError extends Error {}
export class AdminProductIdempotencyConflictError extends Error {}

export async function listProducts(page:number,pageSize:number):Promise<{products:AdminProduct[];total:number}>{const db=getDatabase();const count=await db.prepare("SELECT COUNT(*) AS total FROM products").first<{total:number}>();const result=await db.prepare(`SELECT id,name,slug,sku,short_description,description,image_url,category_id,is_active,revision,updated_at FROM products ORDER BY name COLLATE NOCASE ASC,id ASC LIMIT ? OFFSET ?`).bind(pageSize,(page-1)*pageSize).all<Row>();return{products:result.results.map(toProduct),total:Number(count?.total??0)};}
export async function getProduct(id:number):Promise<AdminProduct|null>{const row=await getDatabase().prepare(`SELECT id,name,slug,sku,short_description,description,image_url,category_id,is_active,revision,updated_at FROM products WHERE id=? LIMIT 1`).bind(id).first<Row>();return row?toProduct(row):null;}
export async function createProduct(raw:unknown,actorSubject:string,requestId:string):Promise<AdminProduct>{const input=normalizeProductInput(raw);const db=getDatabase();await ensureCategory(db,input.categoryId);const slug=await db.prepare("SELECT id FROM products WHERE slug=? LIMIT 1").bind(input.slug).first<{id:number}>();if(slug)throw new AdminProductConflictError("Product slug already exists.");const sku=await db.prepare("SELECT id FROM products WHERE sku=? LIMIT 1").bind(input.sku).first<{id:number}>();if(sku)throw new AdminProductConflictError("Product SKU already exists.");const hash=await sha256(canonicalProductMutationPayload(input));const idem=await existingAudit(db,requestId,hash);if(idem){if(idem.entityType!=="product")throw new AdminProductIdempotencyConflictError("Request ID already used.");const replay=await getProduct(Number(idem.entityKey));if(!replay)throw new AdminProductNotFoundError("Product not found.");return replay;}await db.batch([db.prepare(`INSERT INTO products(name,slug,sku,short_description,description,image_url,category_id,is_active,revision) VALUES(?,?,?,?,?,?,?,?,1)`).bind(input.name,input.slug,input.sku,input.shortDescription,input.description,input.imageUrl,input.categoryId,input.isActive?1:0),db.prepare(`INSERT INTO admin_audit_log(request_id,actor_subject,action,entity_type,entity_key,previous_revision,resulting_revision,payload_sha256) VALUES(?,?, 'create','product',(SELECT CAST(id AS TEXT) FROM products WHERE slug=? LIMIT 1),NULL,1,?)`).bind(requestId,actorSubject,input.slug,hash)]);const created=await getProductBySlug(input.slug);if(!created)throw new Error("Created product could not be loaded.");return created;}
export async function updateProduct(id:number,raw:unknown,actorSubject:string,requestId:string):Promise<AdminProduct>{if(!isRecord(raw))throw new AdminProductValidationError("Invalid product request.");let version:number;try{version=decodeProductVersion(raw.version);}catch{throw new AdminProductValidationError("Invalid version.");}const input=normalizeProductInput(raw);const db=getDatabase();const existing=await getProduct(id);if(!existing)throw new AdminProductNotFoundError("Product not found.");await ensureCategory(db,input.categoryId);const slug=await db.prepare("SELECT id FROM products WHERE slug=? AND id<>? LIMIT 1").bind(input.slug,id).first<{id:number}>();if(slug)throw new AdminProductConflictError("Product slug already exists.");const sku=await db.prepare("SELECT id FROM products WHERE sku=? AND id<>? LIMIT 1").bind(input.sku,id).first<{id:number}>();if(sku)throw new AdminProductConflictError("Product SKU already exists.");const hash=await sha256(canonicalProductMutationPayload(input));const idem=await existingAudit(db,requestId,hash);if(idem){if(idem.entityType!=="product"||idem.entityKey!==String(id))throw new AdminProductIdempotencyConflictError("Request ID already used.");return existing;}
  await db.batch([
    db.prepare(`UPDATE products SET name=?,slug=?,sku=?,short_description=?,description=?,image_url=?,category_id=?,is_active=?,revision=revision+1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=? AND revision=?`).bind(input.name,input.slug,input.sku,input.shortDescription,input.description,input.imageUrl,input.categoryId,input.isActive?1:0,id,version),
    // SQLite changes() observes the immediately preceding UPDATE inside the atomic D1 batch.
    db.prepare(`INSERT INTO admin_audit_log(request_id,actor_subject,action,entity_type,entity_key,previous_revision,resulting_revision,payload_sha256) SELECT ?,?,'update', 'product',CAST(id AS TEXT),revision-1,revision,? FROM products WHERE id=? AND revision=? AND changes()=1`).bind(requestId,actorSubject,hash,id,version+1),
  ]);
  const updated=await getProduct(id);if(!updated)throw new AdminProductNotFoundError("Product not found.");if(updated.version===encodeProductVersion(version))throw new AdminProductConflictError("Product was changed by another operator.");return updated;
}
async function getProductBySlug(slug:string){return getProductFromRow(await getDatabase().prepare(`SELECT id,name,slug,sku,short_description,description,image_url,category_id,is_active,revision,updated_at FROM products WHERE slug=? LIMIT 1`).bind(slug).first<Row>());}
function getProductFromRow(row:Row|null):AdminProduct|null{return row?toProduct(row):null;}
async function ensureCategory(db:Database,id:number|null){if(id===null)return;const row=await db.prepare("SELECT id FROM categories WHERE id=? LIMIT 1").bind(id).first<{id:number}>();if(!row)throw new AdminProductValidationError("Category not found.");}
async function existingAudit(db:Database,requestId:string,payloadHash:string){const row=await db.prepare("SELECT entity_type AS entityType,entity_key AS entityKey,payload_sha256 AS payloadHash FROM admin_audit_log WHERE request_id=? LIMIT 1").bind(requestId).first<{entityType:string;entityKey:string;payloadHash:string}>();if(!row)return null;if(row.payloadHash!==payloadHash)throw new AdminProductIdempotencyConflictError("Request ID already used with different payload.");return row;}
function getDatabase():Database{const {env}=getCloudflareContext();const db=(env as unknown as Env).GIACONG_VN_CATALOG;if(!db)throw new Error("Missing D1 catalog binding.");return db;}
function toProduct(row:Row):AdminProduct{return{id:row.id,name:row.name,slug:row.slug,sku:row.sku,shortDescription:row.short_description,description:row.description,imageUrl:row.image_url,categoryId:row.category_id,isActive:row.is_active===1,version:encodeProductVersion(row.revision),updatedAt:row.updated_at};}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");}
