"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { LayoutDashboard, LogOut, Menu, Package } from "lucide-react";

interface Props { name: string; dashboard: boolean; catalog: boolean; children: React.ReactNode }
export function AdminShell({ name, dashboard, catalog, children }: Props) {
  const [open, setOpen] = useState(false); const router = useRouter(); const pathname = usePathname();
  async function logout() { await fetch("/api/quan-tri/session", { method: "DELETE", headers: { Origin: window.location.origin } }); router.replace("/quan-tri/dang-nhap"); router.refresh(); }
  const nav = [{ href: "/quan-tri", label: "Tổng quan", icon: LayoutDashboard, visible: dashboard }, { href: "/quan-tri/san-pham", label: "Danh mục", icon: Package, visible: catalog }];
  return <div className="min-h-dvh bg-[#f5f5ed] text-[#273326]"><a className="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:m-3 focus:rounded focus:bg-white focus:p-3" href="#admin-main">Bỏ qua điều hướng</a><header className="flex h-14 items-center justify-between border-b border-[#d7d8c9] bg-[#fbfbf5] px-4 lg:hidden"><button aria-expanded={open} aria-controls="admin-nav" className="rounded p-2 focus-visible:outline-2" onClick={() => setOpen(!open)}><Menu aria-hidden /></button><strong className="text-sm tracking-wide">GIA CÔNG · QUẢN TRỊ</strong><button onClick={logout} className="rounded p-2" aria-label="Đăng xuất"><LogOut aria-hidden size={18} /></button></header><aside id="admin-nav" className={`${open ? "block" : "hidden"} fixed inset-x-0 top-14 z-40 border-b border-[#d7d8c9] bg-[#fbfbf5] p-3 lg:static lg:block lg:min-h-dvh lg:w-60 lg:border-b-0 lg:border-r`}><div className="hidden px-3 py-6 lg:block"><p className="text-xs font-semibold tracking-[0.16em] text-[#667151]">GIA CÔNG</p><h1 className="mt-1 text-lg font-semibold">Quản trị B2B</h1></div><nav className="space-y-1">{nav.filter((item) => item.visible).map((item) => { const Icon = item.icon; return <Link onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium ${pathname === item.href ? "bg-[#dfe8bd] text-[#33470d]" : "hover:bg-[#eff0e5]"}`} href={item.href} key={item.href}><Icon size={17} aria-hidden />{item.label}</Link>; })}</nav><div className="mt-6 border-t border-[#d7d8c9] px-3 pt-4 text-xs text-[#667151]"><p className="truncate">{name}</p><button onClick={logout} className="mt-3 inline-flex items-center gap-2 font-medium text-[#3f5712]"><LogOut size={16} aria-hidden />Đăng xuất</button></div></aside><div className="lg:ml-60"><header className="hidden h-14 items-center justify-end border-b border-[#d7d8c9] bg-[#fbfbf5] px-6 text-sm text-[#667151] lg:flex">{name}</header><main id="admin-main" className="mx-auto max-w-6xl p-4 sm:p-6">{children}</main></div></div>;
}
