"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";

export function LoginForm({ returnTo }: { returnTo: string }) {
  // Credentials are intentionally never written to localStorage or sessionStorage.
  const router = useRouter(); const messageRef = useRef<HTMLParagraphElement>(null); const [twoFactor, setTwoFactor] = useState(false); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  useEffect(() => { if (message) messageRef.current?.focus(); }, [message]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const endpoint = twoFactor ? "/api/quan-tri/two-factor" : "/api/quan-tri/session"; const body = twoFactor ? { code: form.get("code") } : { email: form.get("email"), password: form.get("password") }; try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json", Origin: window.location.origin }, body: JSON.stringify(body) }); const payload: unknown = await response.json(); const twoFactorRequired = response.status === 202 && typeof payload === "object" && payload !== null && "data" in payload && typeof payload.data === "object" && payload.data !== null && "two_factor_required" in payload.data && payload.data.two_factor_required === true; if (twoFactorRequired) { setTwoFactor(true); setMessage("Nhập mã xác thực hoặc mã dự phòng gồm 6 chữ số."); return; } if (!response.ok) { const retry = response.headers.get("Retry-After"); setMessage(retry ? `Vui lòng thử lại sau ${retry} giây.` : "Không thể xác thực. Vui lòng kiểm tra thông tin và thử lại."); return; } router.replace(returnTo); router.refresh(); } catch { setMessage("Không thể kết nối dịch vụ quản trị. Vui lòng thử lại."); } finally { setPending(false); } }
  return <form onSubmit={submit} className="mt-6 space-y-4" noValidate>{message && <p ref={messageRef} tabIndex={-1} role="status" className="rounded-md border border-[#c8cbae] bg-[#f4f5df] p-3 text-sm text-[#405018]">{message}</p>}{twoFactor ? <label className="block text-sm font-medium">Mã xác thực hoặc mã dự phòng<input autoFocus inputMode="numeric" pattern="[0-9]{6}" name="code" required maxLength={6} className="mt-1 w-full rounded-md border border-[#afb49e] bg-white px-3 py-2" /></label> : <><label className="block text-sm font-medium">Email<input autoFocus autoComplete="username" name="email" type="email" required className="mt-1 w-full rounded-md border border-[#afb49e] bg-white px-3 py-2" /></label><label className="block text-sm font-medium">Mật khẩu<input autoComplete="current-password" name="password" type="password" required className="mt-1 w-full rounded-md border border-[#afb49e] bg-white px-3 py-2" /></label></>}<button disabled={pending} className="w-full rounded-md bg-[#506d18] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Đang xác thực…" : twoFactor ? "Xác thực" : "Đăng nhập"}</button><p className="text-xs text-[#667151]">Thông tin đăng nhập chỉ được gửi để xác thực phiên hiện tại; không được lưu trên trình duyệt.</p></form>;
}
