// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare build.
import generatedWorker from "./.open-next/worker.js";
import { getRetiredLegacyProductRedirect } from "./src/lib/catalog-legacy-redirects";
import { deliverQueuedLead, type LeadDeliveryEnvironment, type LeadDeliveryMessage } from "./src/lib/lead-delivery-worker";

interface WorkerEnv extends LeadDeliveryEnvironment {
  GIACONG_VN_CATALOG?: CatalogDatabase;
}

interface CatalogPreparedStatement {
  bind(...values: unknown[]): CatalogPreparedStatement;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  run(): Promise<unknown>;
}

interface CatalogDatabase {
  prepare(query: string): CatalogPreparedStatement;
}

interface QueueMessage<T> {
  body: T;
  retry(options?: { delaySeconds?: number }): void;
}

interface QueueBatch<T> {
  messages: QueueMessage<T>[];
  queue: string;
}

interface WorkerExecutionContext {
  passThroughOnException(): void;
  waitUntil(promise: Promise<unknown>): void;
}

const nonIndexableHosts = new Set([
  "admin-staging.kienhieu.id.vn",
  "admin.kienhieu.id.vn",
  "staging.kienhieu.id.vn",
]);

const PUBLIC_DOCUMENT_CACHE_CONTROL = "public, max-age=0, s-maxage=600, stale-while-revalidate=3600";
const CDN_DOCUMENT_CACHE_CONTROL = "public, max-age=86400, stale-while-revalidate=604800";
const publicDocumentCache = (caches as CacheStorage & { default: Cache }).default;

function isPublicDocumentRequest(request: Request): boolean {
  if (request.method !== "GET") return false;

  const url = new URL(request.url);
  if (url.hostname.toLowerCase() !== "kienhieu.id.vn") return false;
  if (!(request.headers.get("Accept") ?? "").includes("text/html")) return false;
  if (request.headers.has("RSC") || url.searchParams.has("_rsc")) return false;
  if (request.headers.has("Cookie") || request.headers.has("Authorization")) return false;
  return true;
}

function isPublicDocumentResponse(response: Response): boolean {
  if (response.status !== 200) return false;
  if (!(response.headers.get("Content-Type") ?? "").includes("text/html")) return false;
  return !response.headers.has("Set-Cookie");
}

function withPublicDocumentCache(request: Request, response: Response): Response {
  if (!isPublicDocumentRequest(request) || !isPublicDocumentResponse(response)) return response;

  const headers = new Headers(response.headers);
  headers.set("Cache-Control", PUBLIC_DOCUMENT_CACHE_CONTROL);
  headers.set("CDN-Cache-Control", CDN_DOCUMENT_CACHE_CONTROL);
  headers.delete("Pragma");
  headers.delete("Expires");
  return new Response(response.body, {
    headers,
    status: response.status,
    statusText: response.statusText,
  });
}

const MARKETING_QUERY_PARAMS = new Set([
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_term",
  "utm_content",
  "fbclid",
  "gclid",
  "gad_source",
  "zarsrc",
  "ref",
  "mc_cid",
  "mc_eid",
]);

function publicDocumentCacheKey(request: Request): Request {
  const url = new URL(request.url);
  for (const param of Array.from(url.searchParams.keys())) {
    if (MARKETING_QUERY_PARAMS.has(param.toLowerCase())) {
      url.searchParams.delete(param);
    }
  }
  return new Request(url.toString(), { method: "GET" });
}

async function readPublicDocumentCache(request: Request): Promise<Response | null> {
  if (!isPublicDocumentRequest(request)) return null;
  try {
    return await publicDocumentCache.match(publicDocumentCacheKey(request)) ?? null;
  } catch (error) {
    console.warn("Public document cache read unavailable.", error);
    return null;
  }
}

function writePublicDocumentCache(
  request: Request,
  response: Response,
  ctx: WorkerExecutionContext,
): void {
  if (!isPublicDocumentRequest(request) || !isPublicDocumentResponse(response)) return;
  ctx.waitUntil(
    publicDocumentCache.put(publicDocumentCacheKey(request), response.clone()).catch((error: unknown) => {
      console.warn("Public document cache write unavailable.", error);
    }),
  );
}

function shouldPreventIndexing(request: Request): boolean {
  return nonIndexableHosts.has(new URL(request.url).hostname.toLowerCase());
}

function withIndexingHeaders(request: Request, response: Response): Response {
  if (!shouldPreventIndexing(request)) return response;
  const headers = new Headers(response.headers);
  headers.set("X-Robots-Tag", "noindex, nofollow, noarchive");
  return new Response(response.body, {
    headers,
    status: response.status,
    statusText: response.statusText,
  });
}

function catalogProductSlug(pathname: string): string | null {
  const match = /^\/san-pham\/([^/]+)\/?$/.exec(pathname);
  if (!match?.[1]) return null;
  try {
    const slug = decodeURIComponent(match[1]).trim();
    return slug || null;
  } catch {
    return null;
  }
}

async function getPublicCatalogProductTarget(database: CatalogDatabase, slug: string): Promise<string | null | undefined> {
  try {
    const row = await database.prepare(`
      SELECT products.slug AS slug
      FROM products
      LEFT JOIN product_slug_redirects
        ON product_slug_redirects.product_id = products.id
        AND product_slug_redirects.old_slug = ?
      WHERE products.is_active = 1
        AND (products.slug = ? OR product_slug_redirects.old_slug = ?)
      ORDER BY CASE WHEN products.slug = ? THEN 0 ELSE 1 END
      LIMIT 1
    `).bind(slug, slug, slug, slug).first<{ slug: string }>();
    return row?.slug ?? null;
  } catch (error) {
    try {
      // Older databases may not have the additive redirect table yet.
      const row = await database.prepare(
        "SELECT slug FROM products WHERE slug = ? AND is_active = 1 LIMIT 1",
      ).bind(slug).first<{ slug: string }>();
      return row?.slug ?? null;
    } catch (fallbackError) {
      console.error("Catalog visibility lookup failed.", {
        error,
        fallbackError,
      });
      return undefined;
    }
  }
}

async function withCatalogProductNotFoundStatus(
  request: Request,
  response: Response,
  env: WorkerEnv,
): Promise<Response> {
  if ((request.method !== "GET" && request.method !== "HEAD") || response.status !== 200) return response;

  const slug = catalogProductSlug(new URL(request.url).pathname);
  if (!slug || !env.GIACONG_VN_CATALOG) return response;

  const targetSlug = await getPublicCatalogProductTarget(env.GIACONG_VN_CATALOG, slug);
  if (targetSlug === undefined) return response;
  if (targetSlug === null) {
    const headers = new Headers(response.headers);
    return new Response(response.body, {
      headers,
      status: 404,
      statusText: "Not Found",
    });
  }
  if (targetSlug !== slug) {
    const location = new URL(request.url);
    location.pathname = `/san-pham/${encodeURIComponent(targetSlug)}/`;
    return withIndexingHeaders(
      request,
      new Response(null, { headers: { Location: location.toString() }, status: 308 }),
    );
  }

  return response;
}

const worker = {
  async fetch(request: Request, env: WorkerEnv, ctx: WorkerExecutionContext): Promise<Response> {
    if (request.method === "GET" || request.method === "HEAD") {
      const redirect = getRetiredLegacyProductRedirect(new URL(request.url));
      if (redirect) {
        return withIndexingHeaders(
          request,
          new Response(null, { headers: { Location: redirect }, status: 308 }),
        );
      }
    }

    const cachedDocument = await readPublicDocumentCache(request);
    if (cachedDocument) {
      const checkedDocument = await withCatalogProductNotFoundStatus(request, cachedDocument, env);
      if (checkedDocument.status === 404) {
        ctx.waitUntil(
          publicDocumentCache.delete(publicDocumentCacheKey(request)).catch(() => {}),
        );
        return checkedDocument;
      }
      if (checkedDocument.status === 308) return checkedDocument;
      return cachedDocument;
    }

    const response = await generatedWorker.fetch(request, env, ctx);

    if (response.headers.has("x-purge-storefront-cache")) {
      const purgePaths = (response.headers.get("x-purge-storefront-cache") ?? "/")
        .split(",")
        .map((path: string) => path.trim())
        .filter(Boolean);
      for (const purgePath of purgePaths) {
        const normalizedPaths = new Set<string>();
        normalizedPaths.add(purgePath);
        if (purgePath !== "/" && purgePath.endsWith("/")) {
          normalizedPaths.add(purgePath.slice(0, -1));
        } else if (purgePath !== "/" && !purgePath.endsWith("/")) {
          normalizedPaths.add(`${purgePath}/`);
        }
        for (const p of normalizedPaths) {
          const purgeKey = new Request(new URL(p, "https://kienhieu.id.vn").toString(), { method: "GET" });
          ctx.waitUntil(
            publicDocumentCache.delete(purgeKey).catch((error: unknown) => {
              console.warn("Public document cache delete failed.", error);
            }),
          );
        }
      }
      const cleanedHeaders = new Headers(response.headers);
      cleanedHeaders.delete("x-purge-storefront-cache");
      return new Response(response.body, {
        headers: cleanedHeaders,
        status: response.status,
        statusText: response.statusText,
      });
    }

    const catalogResponse = await withCatalogProductNotFoundStatus(request, response, env);
    const finalResponse = withPublicDocumentCache(
      request,
      withIndexingHeaders(request, catalogResponse),
    );
    writePublicDocumentCache(request, finalResponse, ctx);
    return finalResponse;
  },

  async queue(batch: QueueBatch<LeadDeliveryMessage>, env: WorkerEnv): Promise<void> {
    if (!env.GIACONG_VN_CATALOG) throw new Error("Missing GIACONG_VN_CATALOG binding.");
    for (const message of batch.messages) {
      try {
        await deliverQueuedLead(message.body, env, env.GIACONG_VN_CATALOG);
      } catch (error) {
        message.retry({ delaySeconds: 60 });
        console.error("Lead queue delivery failed.", {
          error: error instanceof Error ? error.message : "unknown_error",
          leadId: message.body.leadId,
          queue: batch.queue,
        });
      }
    }
  },
};

export default worker;
