// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare build.
import generatedWorker from "./.open-next/worker.js";
import { deliverQueuedLead, type LeadDeliveryEnvironment, type LeadDeliveryMessage } from "./src/lib/lead-delivery-worker";

interface WorkerEnv extends LeadDeliveryEnvironment {
  GIACONG_VN_CATALOG?: CatalogDatabase;
}

interface CatalogPreparedStatement {
  bind(...values: unknown[]): CatalogPreparedStatement;
  first<T = Record<string, unknown>>(): Promise<T | null>;
  run(): Promise<unknown>;
}

interface CatalogDatabase {
  prepare(query: string): CatalogPreparedStatement;
}

interface QueueMessage<T> {
  body: T;
  retry(options?: { delaySeconds?: number }): void;
}

interface QueueBatch<T> {
  messages: QueueMessage<T>[];
  queue: string;
}

interface WorkerExecutionContext {
  passThroughOnException(): void;
  waitUntil(promise: Promise<unknown>): void;
}

const nonIndexableHosts = new Set([
  "admin-staging.kienhieu.id.vn",
  "admin.kienhieu.id.vn",
  "staging.kienhieu.id.vn",
]);

function shouldPreventIndexing(request: Request): boolean {
  return nonIndexableHosts.has(new URL(request.url).hostname.toLowerCase());
}

function withIndexingHeaders(request: Request, response: Response): Response {
  if (!shouldPreventIndexing(request)) return response;
  const headers = new Headers(response.headers);
  headers.set("X-Robots-Tag", "noindex, nofollow, noarchive");
  return new Response(response.body, {
    headers,
    status: response.status,
    statusText: response.statusText,
  });
}

function catalogProductSlug(pathname: string): string | null {
  const match = /^\/san-pham\/([^/]+)$/.exec(pathname);
  if (!match?.[1]) return null;
  try {
    const slug = decodeURIComponent(match[1]).trim();
    return slug || null;
  } catch {
    return null;
  }
}

async function isPublicCatalogProduct(database: CatalogDatabase, slug: string): Promise<boolean | null> {
  try {
    const row = await database.prepare(
      "SELECT id FROM products WHERE slug = ? AND is_active = 1 LIMIT 1",
    ).bind(slug).first<{ id: number }>();
    return row !== null;
  } catch (error) {
    console.error("Catalog visibility lookup failed.", error);
    return null;
  }
}

async function withCatalogProductNotFoundStatus(
  request: Request,
  response: Response,
  env: WorkerEnv,
): Promise<Response> {
  if ((request.method !== "GET" && request.method !== "HEAD") || response.status !== 200) return response;

  const slug = catalogProductSlug(new URL(request.url).pathname);
  if (!slug || !env.GIACONG_VN_CATALOG) return response;

  const isPublic = await isPublicCatalogProduct(env.GIACONG_VN_CATALOG, slug);
  if (isPublic !== false) return response;

  const headers = new Headers(response.headers);
  return new Response(response.body, {
    headers,
    status: 404,
    statusText: "Not Found",
  });
}

const worker = {
  async fetch(request: Request, env: WorkerEnv, ctx: WorkerExecutionContext): Promise<Response> {
    const response = await generatedWorker.fetch(request, env, ctx);
    return withIndexingHeaders(request, await withCatalogProductNotFoundStatus(request, response, env));
  },

  async queue(batch: QueueBatch<LeadDeliveryMessage>, env: WorkerEnv): Promise<void> {
    if (!env.GIACONG_VN_CATALOG) throw new Error("Missing GIACONG_VN_CATALOG binding.");
    for (const message of batch.messages) {
      try {
        await deliverQueuedLead(message.body, env, env.GIACONG_VN_CATALOG);
      } catch (error) {
        message.retry({ delaySeconds: 60 });
        console.error("Lead queue delivery failed.", {
          error: error instanceof Error ? error.message : "unknown_error",
          leadId: message.body.leadId,
          queue: batch.queue,
        });
      }
    }
  },
};

export default worker;
