// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare build.
import generatedWorker from "./.open-next/worker.js";
import { deliverQueuedLead, type LeadDeliveryDatabase, type LeadDeliveryEnvironment, type LeadDeliveryMessage } from "./src/lib/lead-delivery-worker";

interface WorkerEnv extends LeadDeliveryEnvironment {
  GIACONG_VN_CATALOG?: LeadDeliveryDatabase;
}

interface QueueMessage<T> {
  body: T;
  retry(options?: { delaySeconds?: number }): void;
}

interface QueueBatch<T> {
  messages: QueueMessage<T>[];
  queue: string;
}

const worker = {
  fetch: generatedWorker.fetch,

  async queue(batch: QueueBatch<LeadDeliveryMessage>, env: WorkerEnv): Promise<void> {
    if (!env.GIACONG_VN_CATALOG) throw new Error("Missing GIACONG_VN_CATALOG binding.");
    for (const message of batch.messages) {
      try {
        await deliverQueuedLead(message.body, env, env.GIACONG_VN_CATALOG);
      } catch (error) {
        message.retry({ delaySeconds: 60 });
        console.error("Lead queue delivery failed.", {
          error: error instanceof Error ? error.message : "unknown_error",
          leadId: message.body.leadId,
          queue: batch.queue,
        });
      }
    }
  },
};

export default worker;