import Link from "next/link";
import { notFound } from "next/navigation";
import { can, getAdmin, getProducts } from "@/lib/admin-server";

const queryKeys = ["q", "page", "per_page", "sort", "direction"] as const;

export default async function Products({ searchParams }: PageProps<"/quan-tri/san-pham">) {
  const session = await getAdmin();
  if (session.kind !== "authenticated" || !can(session.admin, "b2b.catalog.read")) notFound();
  const values = await searchParams;
  const query = new URLSearchParams();
  for (const key of queryKeys) if (typeof values[key] === "string") query.set(key, values[key]);
  const list = await getProducts(query);
  if (!list) return <section><h1 className="text-2xl font-semibold">Danh mục</h1><p role="alert" className="mt-4 rounded border border-[#d5c3a2] bg-[#fff9ed] p-4">Không thể tải danh mục hoặc phiên đã hết hạn.</p></section>;
  const page = list.meta.current_page;
  const href = (nextPage: number) => { const params = new URLSearchParams(query); params.set("page", String(nextPage)); return `/quan-tri/san-pham?${params}`; };
  return <section><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.14em] text-[#667151]">DANH MỤC</p><h1 className="mt-1 text-2xl font-semibold">Sản phẩm</h1></div><span className="rounded-full bg-[#dfe8bd] px-3 py-1 text-xs font-semibold text-[#405b11]">Chỉ đọc</span></div><form className="mt-5 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><label className="sr-only" htmlFor="q">Tìm sản phẩm</label><input id="q" name="q" defaultValue={query.get("q") ?? ""} maxLength={100} placeholder="Tìm SKU hoặc tên" className="rounded-md border border-[#afb49e] bg-white px-3 py-2 text-sm" /><select aria-label="Sắp xếp" name="sort" defaultValue={query.get("sort") ?? "name"} className="rounded-md border border-[#afb49e] bg-white px-3 py-2 text-sm"><option value="name">Tên</option><option value="id">Mã</option><option value="starting_price">Giá từ</option><option value="variant_count">Biến thể</option></select><button className="rounded-md bg-[#506d18] px-4 py-2 text-sm font-semibold text-white">Lọc</button></form>{list.data.length === 0 ? <p className="mt-6 rounded border border-dashed border-[#afb49e] p-6 text-sm text-[#667151]">Không có sản phẩm phù hợp.</p> : <div className="mt-5 overflow-x-auto rounded-md border border-[#d7d8c9] bg-[#fbfbf5]"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-[#d7d8c9] text-xs uppercase text-[#667151]"><tr><th className="p-3">Sản phẩm</th><th className="p-3">SKU</th><th className="p-3">Biến thể</th><th className="p-3">Khả dụng</th></tr></thead><tbody>{list.data.map((product) => <tr className="border-b border-[#e5e6dc] last:border-0" key={product.id}><td className="p-3"><Link className="font-semibold text-[#3f5712] underline-offset-2 hover:underline" href={`/quan-tri/san-pham/${product.slug}`}>{product.name}</Link><p className="mt-1 text-xs text-[#667151]">{product.categories.map((category) => category.name).join(", ")}</p></td><td className="p-3 font-mono text-xs">{product.sku}</td><td className="p-3">{product.variant_count}</td><td className="p-3">{product.available_variant_count}</td></tr>)}</tbody></table></div>}<nav aria-label="Phân trang danh mục" className="mt-4 flex items-center gap-3 text-sm">{page > 1 ? <Link className="rounded border border-[#afb49e] px-3 py-2" href={href(page - 1)}>Trước</Link> : <span aria-disabled="true" className="rounded border border-[#afb49e] px-3 py-2 opacity-50">Trước</span>}<span>Trang {page}/{list.meta.last_page} · {list.meta.total} sản phẩm</span>{page < list.meta.last_page ? <Link className="rounded border border-[#afb49e] px-3 py-2" href={href(page + 1)}>Sau</Link> : <span aria-disabled="true" className="rounded border border-[#afb49e] px-3 py-2 opacity-50">Sau</span>}</nav></section>;
}
