import { admitRuntimeAdminRequest } from "@/lib/admin-access-runtime";
import { adminFailure, adminSuccess } from "@/lib/admin-api";
import { AdminProductConflictError, AdminProductIdempotencyConflictError, AdminProductNotFoundError, AdminProductValidationError, createProduct, listProducts } from "@/lib/admin-product-repository";

export const dynamic = "force-dynamic";
const MAX_PAGE_SIZE=100;const MAX_BODY_BYTES=64*1024;
export async function GET(request:Request){const requestId=crypto.randomUUID();const admission=await admitRuntimeAdminRequest(request);if(!admission.ok)return adminFailure(requestId,admission.status,admission.code,admission.message);const url=new URL(request.url);const page=bounded(url.searchParams.get("page"),1,1_000_000);const pageSize=bounded(url.searchParams.get("pageSize"),50,MAX_PAGE_SIZE);return adminSuccess(requestId,{...(await listProducts(page,pageSize)),page,pageSize});}
export async function POST(request:Request){const requestId=request.headers.get("x-request-id")?.trim()||crypto.randomUUID();const admission=await admitRuntimeAdminRequest(request);if(!admission.ok)return adminFailure(requestId,admission.status,admission.code,admission.message);if(!isJson(request.headers.get("content-type")))return adminFailure(requestId,415,"UNSUPPORTED_MEDIA","Content-Type không được hỗ trợ.");try{return adminSuccess(requestId,await createProduct(await readJson(request),admission.actor.subject,requestId),201);}catch(error){return mapError(requestId,error);}}
function bounded(value:string|null,fallback:number,max:number){if(value===null||value==="")return fallback;const n=Number(value);return Number.isSafeInteger(n)&&n>=1&&n<=max?n:fallback;}
function isJson(v:string|null){return Boolean(v&&v.toLowerCase().split(";",1)[0].trim()==="application/json");}
async function readJson(request:Request){const length=Number(request.headers.get("content-length"));if(Number.isFinite(length)&&length>MAX_BODY_BYTES)throw new PayloadTooLargeError();const bytes=await request.arrayBuffer();if(bytes.byteLength>MAX_BODY_BYTES)throw new PayloadTooLargeError();try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw new AdminProductValidationError("Malformed JSON request.");}}
function mapError(id:string,error:unknown){if(error instanceof PayloadTooLargeError)return adminFailure(id,413,"PAYLOAD_TOO_LARGE","Request quá lớn.");if(error instanceof AdminProductConflictError)return adminFailure(id,409,"UNIQUE_CONFLICT","Sản phẩm đã thay đổi hoặc slug/SKU đã tồn tại.");if(error instanceof AdminProductIdempotencyConflictError)return adminFailure(id,409,"IDEMPOTENCY_CONFLICT","Request ID đã được sử dụng cho payload khác.");if(error instanceof AdminProductNotFoundError)return adminFailure(id,404,"NOT_FOUND","Không tìm thấy sản phẩm.");if(error instanceof AdminProductValidationError||error instanceof Error&&/required|invalid|must be|exceeds|slug|sku|category/i.test(error.message))return adminFailure(id,422,"VALIDATION_ERROR","Dữ liệu sản phẩm không hợp lệ.");return adminFailure(id,500,"INTERNAL_ERROR","Không thể hoàn tất thao tác quản trị.");}
class PayloadTooLargeError extends Error {}
